on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 16.x
          - 15.x
          - 14.x
    name: "Node Version: ${{ matrix.node }}"
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Npm and Node Setup
        uses: actions/setup-node@v2.2.0
        with:
          node-version: "${{ matrix.node }}"

      - name: Install Packages
        run: npm install

      - name: NPM test
        run: npm run test
  Publish:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout 
        uses: actions/checkout@master

      - name: Npm and Node Setup
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Edit Version
        run: |
          actions_id="${{ github.run_id }}" node .github/edit_package_json.js
      - name: Install Packages
        run: npm install

      - name: NPM Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ORG_TOKEN }}
