on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Npm and Node Setup
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16.x

      - name: Install Packages
        run: npm install

      - name: NPM test
        run: npm run test
  Publish:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout 
        uses: actions/checkout@master

      - name: Npm and Node Setup
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Edit Version
        run: |
          actions_id="${{ github.run_id }}" node .github/edit_package_json.js
      - name: Install Packages
        run: npm install

      - name: NPM Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DOCKER_ORG_PASS }}
